### PR TITLE
Switch order of spread to allow given props to override

### LINKED ISSUE #614: Viewbox on FontAwesomeIcon changed to v3.0.0
**Describe the bug**
Since v3.0.0 the created SVG will always have the default viewbox. Therefore it is not possible anymore to change the viewbox.

**Reproducible test case**
package.json
```json
{
  "name": "my-app",
  "private": true,
  "version": "0.0.0",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "tsc -b && vite build",
    "lint": "eslint .",
    "preview": "vite preview"
  },
  "dependencies": {
    "@fortawesome/fontawesome-free": "^7.1.0",
    "@fortawesome/fontawesome-svg-core": "^7.1.0",
    "@fortawesome/free-regular-svg-icons": "^7.1.0",
    "@fortawesome/free-solid-svg-icons": "^7.1.0",
    "@fortawesome/react-fontawesome": "^0.2.6",
    "react": "^19.2.0",
    "react-dom": "^19.2.0"
  },
  "devDependencies": {
    "@eslint/js": "^9.39.1",
    "@types/node": "^24.10.1",
    "@types/react": "^19.2.5",
    "@types/react-dom": "^19.2.3",
    "@vitejs/plugin-react": "^5.1.1",
    "eslint": "^9.39.1",
    "eslint-plugin-react-hooks": "^7.0.1",
    "eslint-plugin-react-refresh": "^0.4.24",
    "globals": "^16.5.0",
    "typescript": "~5.9.3",
    "typescript-eslint": "^8.46.4",
    "vite": "^7.2.4"
  }
}
```

App.tsx
```tsx
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faPen } from '@fortawesome/free-solid-svg-icons'

function App() {
  return (
    <>
      <FontAwesomeIcon icon={faPen} color="white" viewBox="-300 -120 128 128" />
      <FontAwesomeIcon icon={faPen} color="white" viewBox='' />
    </>
  )
}

export default App
```

**Expected behavior**
I expect FontawesomIcon to forward the viewbox property to the created svg element, as it was prior to v3.0.0 therefore allowing the change of the viewbox.

Rendering the example with v3.x.x  results in

Image 

where both svgs have the viewbox `0 0 256 256`.

In 0.2.6 this resulted in

Image

where the first svg has the viewbox "-300 -100 128 128" and the second one has none at all.

**Desktop (please complete the following information):**
* Firefox 146
* Chrome 143

### PR DESCRIPTION
**Pull request by robmadole**
Fixes #614 

@charles4221 throwing this one at you for a quick review.

### CODE REVIEW

File: src/converter.ts [hunk 1]
```diff
@@ -139,7 +139,7 @@ export function convert<
     attrs['aria-hidden'] = 'false'
   }
 
-  return createElement(element.tag, { ...remaining, ...attrs }, ...children)
+  return createElement(element.tag, { ...attrs, ...remaining }, ...children)
```
Comment (robmadole) [inline src/converter.ts]: Switching these allows any prop that is generated for the `<svg>` to be overridden. This is a bit of an edge case but proved frustrating for the OP.

Comment (charles4221) [reply src/converter.ts]: Ooof, massive rookie mistake from me there :joy: thanks mate!
